version: "3.8"
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:      
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "15672:15672"
      - "15691:15691"
      - "15692:15692"
      - "25672:25672"
      
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  mongo-express:
    image: mongo-express
    container_name: express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
